INSERT INTO GROUPS (GROUP_NAME ) VALUES ( 'Java' );
INSERT INTO GROUPS (GROUP_NAME ) VALUES ( '.NET' );
INSERT INTO GROUPS (GROUP_NAME ) VALUES ( '.UI' );

SELECT * FROM groups;

INSERT INTO students (USER_NAME, FIRST_NAME, LAST_NAME, GROUP_ID)
VALUES ('jdoe', 'John', 'Doe', 1);

INSERT INTO students (USER_NAME, FIRST_NAME, LAST_NAME, GROUP_ID)
VALUES ('mstuard', 'Martha', 'Stuart', 1);

INSERT INTO students (USER_NAME, FIRST_NAME, LAST_NAME, GROUP_ID)
VALUES ('wbloke', 'William', 'Bloke', 2);

SELECT * FROM students;
